import "server-only";

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";

import { hashPassword, verifyPassword } from "./password";
import { digestSessionToken } from "./session";
import type { ActivityRow } from "./activity-service";
import type { TeamRow } from "./team-service";
import type { TaskRow } from "./task-service";
import type { PollOptionRow, PollRow, PollSnapshot, VoteCommandResult, VoteRow } from "./vote-service";
import { SupabaseRestError } from "./supabase-rest";

export class FormalBoardLocalError extends SupabaseRestError {
  constructor(message: string, status = 400) { super(message, status); this.name = "FormalBoardLocalError"; }
}

type User = { id: string; login_id: string; login_id_normalized: string; status: string; created_at: string; password_hash: string; contact_value: string; };
type Session = { user_id: string; token_digest: string; expires_at: string; revoked_at: string | null };
type Activity = ActivityRow & { owner_id: string; description: string; deadline_at: string | null };
type Membership = { id: string; activity_id: string; user_id: string; role: "host" | "member" | "collaborator"; status: "active" | "left" | "removed" };
type TeamMember = { user_id: string; role: "captain" | "member"; status: "active" | "removed" };
type Team = TeamRow & { activity_id: string; captain_id: string; description: string; data_version: number; deleted: boolean; members: TeamMember[] };
type Task = TaskRow & { activity_id: string; description: string; data_version: number; deleted: boolean; assignees: string[] };
type InviteUse = { user_id: string; membership_id: string; team_id: string | null };
type Invite = { id: string; activity_id: string; token_digest: string; token_hint: string; role: "member" | "collaborator"; expires_at: string | null; max_uses: number; use_count: number; status: string; team_id?: string | null; team_name?: string | null; invite_type?: "activity_team" | "team_member" | "activity_member"; uses?: InviteUse[] };
type Poll = PollRow & { activity_id: string };
type Option = PollOptionRow;
type Vote = VoteRow;
type Audit = { id: string; activity_id: string | null; actor_user_id: string | null; action: string; target_type: string; target_id: string | null; request_id: string; result: "success" | "failure"; created_at: string };
type Attachment = { id: string; activity_id: string; team_id: string | null; task_id: string | null; uploaded_by: string; original_name: string; media_type: string; size_bytes: number; sha256: string; status: string; created_at: string };
type State = { users: User[]; sessions: Session[]; activities: Activity[]; memberships: Membership[]; teams: Team[]; tasks: Task[]; invites: Invite[]; polls: Poll[]; options: Option[]; votes: Vote[]; audits: Audit[]; attachments: Attachment[] };

const empty = (): State => ({ users: [], sessions: [], activities: [], memberships: [], teams: [], tasks: [], invites: [], polls: [], options: [], votes: [], audits: [], attachments: [] });
const filePath = join(process.cwd(), "data", "formal-board", "local-store.json");
let state: State | null = null;
function load(): State { if (state) return state; try { state = JSON.parse(readFileSync(filePath, "utf8")) as State; } catch { state = empty(); } return state; }
function save() { const dir = dirname(filePath); if (!existsSync(dir)) mkdirSync(dir, { recursive: true }); const tmp = `${filePath}.tmp`; writeFileSync(tmp, JSON.stringify(load(), null, 2), "utf8"); renameSync(tmp, filePath); }
function now() { return new Date().toISOString(); }
function id() { return randomUUID(); }
function write<T>(fn: (s: State) => T): T { const result = fn(load()); save(); return result; }
function read<T>(fn: (s: State) => T): T { return fn(load()); }
function user(s: State, userId: string) { const found = s.users.find((x) => x.id === userId && x.status === "active"); if (!found) throw new FormalBoardLocalError("用户不存在。", 404); return found; }
function member(s: State, userId: string, activityId: string) { return s.memberships.find((x) => x.user_id === userId && x.activity_id === activityId && x.status === "active") ?? null; }
function activity(s: State, activityId: string) { const found = s.activities.find((x) => x.id === activityId && x.status !== "deleted"); if (!found) throw new FormalBoardLocalError("活动不存在。", 404); return found; }
function audit(s: State, activityId: string | null, actor: string | null, action: string, targetType: string, targetId: string | null, requestId: string) { s.audits.unshift({ id: id(), activity_id: activityId, actor_user_id: actor, action, target_type: targetType, target_id: targetId, request_id: requestId, result: "success", created_at: now() }); }

export async function localRegister(loginId: string, password: string) { const passwordHash = await hashPassword(password); return write((s) => { if (s.users.some((x) => x.login_id_normalized === loginId.toLowerCase())) throw new FormalBoardLocalError("账号已存在。", 409); const row: User = { id: id(), login_id: loginId, login_id_normalized: loginId.toLowerCase(), status: "active", created_at: now(), password_hash: passwordHash, contact_value: "" }; s.users.push(row); return row; }); }
export async function localLogin(loginId: string, password: string, requestId: string) { const found = read((s) => s.users.find((x) => x.login_id_normalized === loginId.toLowerCase())); if (!found || found.status !== "active" || !(await verifyPassword(password, found.password_hash))) { write((s) => { audit(s, null, null, "auth.login", "user", null, requestId); }); return null; } const token = (await import("./session")).createSessionToken(); write((s) => { s.sessions.push({ user_id: found.id, token_digest: digestSessionToken(token), expires_at: new Date(Date.now() + 30 * 86400000).toISOString(), revoked_at: null }); audit(s, null, found.id, "auth.login", "session", null, requestId); }); return { user: found, token }; }
export function localCurrent(token: string) { return read((s) => { const session = s.sessions.find((x) => x.token_digest === digestSessionToken(token) && !x.revoked_at && Date.parse(x.expires_at) > Date.now()); if (!session) return null; const found = s.users.find((x) => x.id === session.user_id && x.status === "active"); return found ? { user: found, session } : null; }); }
export function localRevoke(token: string, requestId: string) { write((s) => { const session = s.sessions.find((x) => x.token_digest === digestSessionToken(token)); if (session) { session.revoked_at = now(); audit(s, null, session.user_id, "auth.logout", "session", null, requestId); } }); }

export function localCreateActivity(input: { userId: string; title: string; description: string; deadlineAt?: string | null; requestId: string }) { return write((s) => { user(s, input.userId); const created = now(); const row: Activity = { id: id(), title: input.title, description: input.description, status: "draft", data_version: 1, role: "host", updated_at: created, deadline_at: input.deadlineAt ?? null, owner_id: input.userId }; s.activities.unshift(row); s.memberships.push({ id: id(), activity_id: row.id, user_id: input.userId, role: "host", status: "active" }); audit(s, row.id, input.userId, "activity.create", "activity", row.id, input.requestId); return row; }); }
export function localListActivities(userId: string) { return read((s) => s.activities.filter((a) => a.status !== "deleted" && member(s, userId, a.id)).map((a) => ({ ...a, role: member(s, userId, a.id)?.role ?? "member" }))); }
export function localUpdateActivity(input: { userId: string; activityId: string; title: string; description: string; deadlineAt?: string | null; status: string; expectedVersion: number; requestId: string }) { return write((s) => { const a = activity(s, input.activityId); const m = member(s, input.userId, a.id); if (!m || m.role !== "host") throw new FormalBoardLocalError("只有主持人可以编辑活动。", 403); if (a.data_version !== input.expectedVersion) throw new FormalBoardLocalError("活动已被其他人修改，请刷新后重试。", 409); Object.assign(a, { title: input.title, description: input.description, deadline_at: input.deadlineAt ?? null, status: input.status, data_version: a.data_version + 1, updated_at: now() }); audit(s, a.id, input.userId, "activity.update", "activity", a.id, input.requestId); return a; }); }

export function localListTeams(userId: string, activityId: string) { return read((s) => { const m = member(s, userId, activityId); if (!m) throw new FormalBoardLocalError("无权访问该活动。", 403); return s.teams.filter((t) => t.activity_id === activityId && !t.deleted).map((t) => ({ ...t, team_role: t.members?.find((x) => x.user_id === userId && x.status === "active")?.role ?? (t.captain_id === userId ? "captain" : "member"), task_count: s.tasks.filter((x) => x.team_id === t.id && !x.deleted).length })); }); }
export function localCreateTeam(input: { userId: string; activityId: string; name: string; description: string; requestId: string }) { return write((s) => { const m = member(s, input.userId, input.activityId); if (!m || m.role !== "host") throw new FormalBoardLocalError("只有主持人可以创建队伍。", 403); if (s.teams.some((t) => t.activity_id === input.activityId && !t.deleted && t.name === input.name)) throw new FormalBoardLocalError("队伍名称已存在。", 409); const row: Team = { id: id(), activity_id: input.activityId, name: input.name, description: input.description, captain_id: input.userId, task_count: 0, sort_order: s.teams.filter((t) => t.activity_id === input.activityId).length, data_version: 1, deleted: false, members: [{ user_id: input.userId, role: "captain", status: "active" }] }; s.teams.push(row); audit(s, input.activityId, input.userId, "team.create", "team", row.id, input.requestId); return row; }); }
export function localUpdateTeam(input: { userId: string; activityId: string; teamId: string; name: string; description: string; expectedVersion: number; requestId: string }) { return write((s) => { const t = s.teams.find((x) => x.id === input.teamId && x.activity_id === input.activityId && !x.deleted); if (!t) throw new FormalBoardLocalError("队伍不存在。", 404); if (t.captain_id !== input.userId || t.data_version !== input.expectedVersion) throw new FormalBoardLocalError(t.captain_id !== input.userId ? "只有当前队伍的队长可以编辑队伍。" : "队伍已被其他人修改，请刷新后重试。", t.captain_id !== input.userId ? 403 : 409); Object.assign(t, { name: input.name, description: input.description, data_version: t.data_version + 1 }); audit(s, input.activityId, input.userId, "team.update", "team", t.id, input.requestId); return t; }); }
export function localDeleteTeam(input: { userId: string; activityId: string; teamId: string; expectedVersion: number; requestId: string }) { write((s) => { const t = s.teams.find((x) => x.id === input.teamId && x.activity_id === input.activityId && !x.deleted); if (!t) throw new FormalBoardLocalError("队伍不存在。", 404); if (t.captain_id !== input.userId) throw new FormalBoardLocalError("只有当前队伍的队长可以删除队伍。", 403); if (t.data_version !== input.expectedVersion) throw new FormalBoardLocalError("队伍已被其他人修改，请刷新后重试。", 409); t.deleted = true; audit(s, input.activityId, input.userId, "team.delete", "team", t.id, input.requestId); }); return []; }

export function localListTasks(userId: string, activityId: string, teamId: string) { return read((s) => { if (!member(s, userId, activityId)) throw new FormalBoardLocalError("无权访问该活动。", 403); return s.tasks.filter((t) => t.activity_id === activityId && t.team_id === teamId && !t.deleted).map((t) => ({ ...t, assigned_to_current_user: t.assignees.includes(userId) })); }); }
function canTeamWrite(s: State, userId: string, activityId: string, teamId: string) { const m = member(s, userId, activityId); const t = s.teams.find((x) => x.id === teamId && x.activity_id === activityId && !x.deleted); const teamMember = t?.members?.find((x) => x.user_id === userId && x.status === "active"); if (!m || !t || teamMember?.role !== "captain") throw new FormalBoardLocalError("只有当前队伍的队长可以修改队伍任务。", 403); return t; }
export function localCreateTask(input: { userId: string; activityId: string; teamId: string; title: string; description: string; requestId: string }) { return write((s) => { canTeamWrite(s, input.userId, input.activityId, input.teamId); const row: Task = { id: id(), activity_id: input.activityId, team_id: input.teamId, title: input.title, description: input.description, status: "todo", progress: 0, data_version: 1, deleted: false, assignees: [] }; s.tasks.push(row); audit(s, input.activityId, input.userId, "task.create", "task", row.id, input.requestId); return row; }); }
function updateTask(input: { userId: string; activityId: string; taskId: string; expectedVersion: number; requestId: string; patch: Partial<Task>; allowAssigned?: boolean }) { return write((s) => { const t = s.tasks.find((x) => x.id === input.taskId && x.activity_id === input.activityId && !x.deleted); if (!t) throw new FormalBoardLocalError("任务不存在。", 404); const team = s.teams.find((x) => x.id === t.team_id && !x.deleted); const teamMember = team?.members?.find((x) => x.user_id === input.userId && x.status === "active"); const assigned = t.assignees.includes(input.userId); if (input.allowAssigned ? (!teamMember || (!assigned && teamMember.role !== "captain")) : (!teamMember || teamMember.role !== "captain")) throw new FormalBoardLocalError("无权修改该任务。", 403); if (t.data_version !== input.expectedVersion) throw new FormalBoardLocalError("任务已被其他人修改，请刷新后重试。", 409); Object.assign(t, input.patch, { data_version: t.data_version + 1 }); audit(s, input.activityId, input.userId, "task.update", "task", t.id, input.requestId); return t; }); }
export const localUpdateTaskStatus = (i: { userId: string; activityId: string; taskId: string; status: string; expectedVersion: number; requestId: string }) => updateTask({ ...i, patch: { status: i.status as TaskRow["status"] } });
export const localUpdateTaskProgress = (i: { userId: string; activityId: string; taskId: string; status: string; progress: number; expectedVersion: number; requestId: string }) => updateTask({ ...i, allowAssigned: true, patch: { status: i.status as TaskRow["status"], progress: i.progress } });
export const localUpdateTaskDetails = (i: { userId: string; activityId: string; taskId: string; title: string; description: string; expectedVersion: number; requestId: string }) => updateTask({ ...i, patch: { title: i.title, description: i.description } });

export function localCreatePoll(input: { userId: string; activityId: string; title: string; description: string; hostEligible: boolean; allowSelfVote: boolean; resultMode: PollRow["result_mode"]; requestId: string }) { return write((s) => { const m = member(s, input.userId, input.activityId); if (!m || m.role !== "host") throw new FormalBoardLocalError("只有主持人可以创建投票。", 403); const t = now(); const row: Poll = { id: id(), activity_id: input.activityId, title: input.title, description: input.description, choice_mode: "single-choice", status: "draft", result_mode: input.resultMode, host_eligible: input.hostEligible, allow_self_vote: input.allowSelfVote, data_version: 1, created_by: input.userId, created_at: t, updated_at: t, closed_at: null }; s.polls.push(row); audit(s, input.activityId, input.userId, "poll.create", "poll", row.id, input.requestId); return row; }); }
export function localCreateOption(i: { userId: string; pollId: string; title: string; description: string; link: string | null; submittedBy: string | null; requestId: string }) { return write((s) => { const p = s.polls.find((x) => x.id === i.pollId); if (!p) throw new FormalBoardLocalError("投票不存在。", 404); const m = member(s, i.userId, p.activity_id); if (!m || m.role !== "host" || p.status !== "draft") throw new FormalBoardLocalError("只有草稿投票的主持人可以添加候选项。", 403); if (i.submittedBy && !member(s, i.submittedBy, p.activity_id)) throw new FormalBoardLocalError("提交者不是当前活动成员。", 400); const t = now(); const row: Option = { id: id(), poll_id: p.id, title: i.title, description: i.description, link: i.link, submitted_by: i.submittedBy, status: "published", data_version: 1, created_at: t, updated_at: t }; s.options.push(row); audit(s, p.activity_id, i.userId, "poll.option.create", "poll_option", row.id, i.requestId); return row; }); }
export function localUpdatePoll(i: { userId: string; pollId: string; title?: string; description?: string; hostEligible?: boolean; allowSelfVote?: boolean; resultMode?: PollRow["result_mode"]; open: boolean; close: boolean; expectedVersion: number; requestId: string }) { return write((s) => { const p = s.polls.find((x) => x.id === i.pollId); if (!p) throw new FormalBoardLocalError("投票不存在。", 404); const m = member(s, i.userId, p.activity_id); if (!m || m.role !== "host") throw new FormalBoardLocalError("只有主持人可以编辑投票。", 403); if (p.data_version !== i.expectedVersion) throw new FormalBoardLocalError("投票已被其他人修改，请刷新后重试。", 409); if (p.status !== "draft" && !i.close) throw new FormalBoardLocalError("投票规则已锁定。", 409); Object.assign(p, { title: i.title ?? p.title, description: i.description ?? p.description, host_eligible: i.hostEligible ?? p.host_eligible, allow_self_vote: i.allowSelfVote ?? p.allow_self_vote, result_mode: i.resultMode ?? p.result_mode, status: i.close ? "closed" : i.open ? "open" : p.status, closed_at: i.close ? now() : p.closed_at, data_version: p.data_version + 1, updated_at: now() }); audit(s, p.activity_id, i.userId, i.close ? "poll.close" : "poll.update", "poll", p.id, i.requestId); return p; }); }
export function localUpdateOption(i: { userId: string; pollId: string; optionId: string; title: string; description: string; link: string | null; submittedBy: string | null; status: Option["status"]; expectedVersion: number; requestId: string }) { return write((s) => { const o = s.options.find((x) => x.id === i.optionId && x.poll_id === i.pollId); const p = s.polls.find((x) => x.id === i.pollId); if (!o || !p) throw new FormalBoardLocalError("候选项不存在。", 404); const m = member(s, i.userId, p.activity_id); if (!m || m.role !== "host" || p.status !== "draft") throw new FormalBoardLocalError("只有草稿投票的主持人可以编辑候选项。", 403); if (o.data_version !== i.expectedVersion) throw new FormalBoardLocalError("候选项已被其他人修改，请刷新后重试。", 409); Object.assign(o, { title: i.title, description: i.description, link: i.link, submitted_by: i.submittedBy, status: i.status, data_version: o.data_version + 1, updated_at: now() }); return o; }); }
function snapshot(s: State, p: Poll, userId: string): PollSnapshot { const votes = s.votes.filter((v) => v.poll_id === p.id); const viewer = votes.find((v) => v.voter_user_id === userId) ?? null; return { poll: p, options: s.options.filter((o) => o.poll_id === p.id && o.status !== "removed"), results: s.options.filter((o) => o.poll_id === p.id && o.status === "published").map((o) => ({ optionId: o.id, count: p.result_mode === "hidden" || (p.result_mode === "final" && p.status !== "closed") ? null : votes.filter((v) => v.option_id === o.id && v.status === "active").length, recordedForViewer: votes.some((v) => v.voter_user_id === userId && v.option_id === o.id) })), viewerVote: viewer ? { voteId: viewer.id, optionId: viewer.option_id, status: viewer.status } : null }; }
export function localSnapshot(userId: string, pollId: string) { return read((s) => { const p = s.polls.find((x) => x.id === pollId); if (!p || !member(s, userId, p.activity_id)) throw new FormalBoardLocalError("无权访问该投票。", 403); return snapshot(s, p, userId); }); }
export function localCastVote(i: { userId: string; pollId: string; optionId: string; requestId: string }): VoteCommandResult { return write((s) => { const p = s.polls.find((x) => x.id === i.pollId); const o = s.options.find((x) => x.id === i.optionId && x.poll_id === i.pollId && x.status === "published"); const m = p && member(s, i.userId, p.activity_id); const a = p ? activity(s, p.activity_id) : null; if (!p || !o || !m || !a || p.status !== "open" || a.status !== "open") throw new FormalBoardLocalError("投票当前不可用。", 409); if (m.role === "host" && !p.host_eligible) throw new FormalBoardLocalError("主持人未获得投票资格。", 403); if (!p.allow_self_vote && o.submitted_by === i.userId) throw new FormalBoardLocalError("不允许给自己的作品投票。", 403); const existing = s.votes.find((v) => v.poll_id === p.id && v.voter_user_id === i.userId); if (existing) return { code: "ALREADY_VOTED", vote: existing, message: "该成员已经投过票。" }; const vote: Vote = { id: id(), poll_id: p.id, option_id: o.id, voter_user_id: i.userId, status: "active", cast_at: now(), voided_at: null, void_reason: null }; s.votes.push(vote); audit(s, p.activity_id, i.userId, "vote.cast", "vote", vote.id, i.requestId); return { code: "RECORDED", vote, message: "投票已记录。" }; }); }
export function localVoidVote(i: { userId: string; pollId: string; voteId: string; reason: string; requestId: string }) { return write((s) => { const p = s.polls.find((x) => x.id === i.pollId); const v = s.votes.find((x) => x.id === i.voteId && x.poll_id === i.pollId); const m = p && member(s, i.userId, p.activity_id); if (!p || !v || !m || m.role !== "host" || p.status === "closed") throw new FormalBoardLocalError("无权作废该投票。", 403); v.status = "voided"; v.voided_at = now(); v.void_reason = i.reason; audit(s, p.activity_id, i.userId, "vote.void", "vote", v.id, i.requestId); return { voided: true as const, vote: v }; }); }

export function localListAudit(userId: string, activityId?: string) { return read((s) => s.audits.filter((a) => activityId ? a.activity_id === activityId && member(s, userId, activityId)?.role === "host" : a.actor_user_id === userId).slice(0, 100)); }
export function localContact(userId: string) { return read((s) => ({ value: s.users.find((u) => u.id === userId)?.contact_value ?? "", visibility: "private" as const })); }
export function localSetContact(userId: string, value: string) { write((s) => { const u = user(s, userId); u.contact_value = value; }); return { value, visibility: "private" as const }; }
export function localAttachments(userId: string, activityId: string) { return read((s) => { if (!member(s, userId, activityId)) throw new FormalBoardLocalError("无权访问该活动。", 403); return s.attachments.filter((x) => x.activity_id === activityId && x.status === "active"); }); }
export function localTeamMembers(userId: string, activityId: string, teamId: string, taskId: string) { return read((s) => { const m = member(s, userId, activityId); const team = s.teams.find((x) => x.id === teamId && !x.deleted); const task = s.tasks.find((x) => x.id === taskId && x.team_id === teamId && !x.deleted); if (!m || !team || !task) throw new FormalBoardLocalError("无权读取任务成员。", 403); const members = (team.members ?? []).filter((x) => x.status === "active").map((x) => { const membership = s.memberships.find((memberRow) => memberRow.user_id === x.user_id && memberRow.activity_id === activityId && memberRow.status === "active"); return membership ? { membership_id: membership.id, user_id: membership.user_id, display_name: s.users.find((u) => u.id === membership.user_id)?.login_id ?? "成员", role: x.role as "captain" | "member" } : null; }).filter((x): x is { membership_id: string; user_id: string; display_name: string; role: "captain" | "member" } => Boolean(x)); return { members, membershipIds: task.assignees.map((uid) => s.memberships.find((x) => x.user_id === uid && x.activity_id === activityId)?.id).filter((x): x is string => Boolean(x)) }; }); }
export function localAssignTaskMembers(userId: string, activityId: string, taskId: string, membershipIds: string[], requestId: string) { write((s) => { const task = s.tasks.find((x) => x.id === taskId && x.activity_id === activityId && !x.deleted); if (!task) throw new FormalBoardLocalError("任务不存在。", 404); const team = canTeamWrite(s, userId, activityId, task.team_id); const captain = team.members?.some((x) => x.user_id === userId && x.role === "captain" && x.status === "active"); if (!captain) throw new FormalBoardLocalError("只有队长可以分配任务。", 403); const ids = (team.members ?? []).filter((x) => membershipIds.some((membershipId) => s.memberships.find((m) => m.id === membershipId)?.user_id === x.user_id) && x.status === "active").map((x) => x.user_id); task.assignees = ids; audit(s, activityId, userId, "task.update", "task", task.id, requestId); }); return { assigned: membershipIds.length }; }

export function localCreateInvite(input: { userId: string; activityId: string; inviteType: "activity_team" | "team_member"; teamId?: string | null; teamName?: string | null; expiresAt: string | null; maxUses: number; tokenDigest: string; tokenHint: string; requestId: string }) { return write((s) => { const m = member(s, input.userId, input.activityId); const team = input.teamId ? s.teams.find((x) => x.id === input.teamId && x.activity_id === input.activityId && !x.deleted) : null; if (!m || (input.inviteType === "activity_team" ? m.role !== "host" : team?.members?.find((x) => x.user_id === input.userId && x.role === "captain" && x.status === "active") === undefined)) throw new FormalBoardLocalError(input.inviteType === "activity_team" ? "只有主持人可以生成邀请。" : "只有当前队伍的队长可以生成队员邀请。", 403); if (input.inviteType === "activity_team" && (!input.teamName?.trim() || input.teamId)) throw new FormalBoardLocalError("队伍邀请参数无效。", 400); if (input.inviteType === "team_member" && (!team || !input.teamId)) throw new FormalBoardLocalError("队伍邀请参数无效。", 400); const invite: Invite = { id: id(), activity_id: input.activityId, token_digest: input.tokenDigest, token_hint: input.tokenHint, role: input.inviteType === "activity_team" ? "collaborator" : "member", expires_at: input.expiresAt, max_uses: input.maxUses, use_count: 0, status: "active", invite_type: input.inviteType, team_id: input.teamId ?? null, team_name: input.teamName?.trim() ?? null, uses: [] }; s.invites.push(invite); audit(s, input.activityId, input.userId, "membership.invite", "activity_invite", invite.id, input.requestId); const { token_digest: _tokenDigest, uses: _uses, ...publicInvite } = invite; void _tokenDigest; void _uses; return publicInvite; }); }
export function localJoinInvite(input: { userId: string; tokenDigest: string; requestId: string }) { return write((s) => { const invite = s.invites.find((x) => x.token_digest === input.tokenDigest); if (!invite) throw new FormalBoardLocalError("邀请无效、已过期、已撤销或已达到使用次数。", 409); const prior = (invite.uses ?? []).find((x) => x.user_id === input.userId); if (prior) return [{ activity_id: invite.activity_id, membership_id: prior.membership_id, role: invite.role, already_joined: true, team_id: prior.team_id ?? "", invite_type: invite.invite_type ?? "activity_member" }]; if (invite.status !== "active" || (invite.expires_at && Date.parse(invite.expires_at) <= Date.now()) || invite.use_count >= invite.max_uses) throw new FormalBoardLocalError("邀请无效、已过期、已撤销或已达到使用次数。", 409); const existing = member(s, input.userId, invite.activity_id); let membership = existing; if (!membership) { membership = { id: id(), activity_id: invite.activity_id, user_id: input.userId, role: invite.role, status: "active" }; s.memberships.push(membership); } else if (invite.invite_type === "activity_team") { membership.role = "collaborator"; membership.status = "active"; } let acceptedTeamId: string | null = null; if (invite.invite_type === "activity_team") { const team: Team = { id: id(), activity_id: invite.activity_id, name: invite.team_name ?? "未命名队伍", description: "", captain_id: input.userId, task_count: 0, sort_order: s.teams.filter((x) => x.activity_id === invite.activity_id).length, data_version: 1, deleted: false, members: [{ user_id: input.userId, role: "captain", status: "active" }] }; s.teams.push(team); acceptedTeamId = team.id; } else if (invite.invite_type === "team_member") { const team = s.teams.find((x) => x.id === invite.team_id && x.activity_id === invite.activity_id && !x.deleted); if (!team) throw new FormalBoardLocalError("邀请对应的队伍不存在。", 409); if (!team.members?.some((x) => x.user_id === input.userId && x.status === "active")) team.members = [...(team.members ?? []), { user_id: input.userId, role: "member", status: "active" }]; acceptedTeamId = team.id; } invite.uses = [...(invite.uses ?? []), { user_id: input.userId, membership_id: membership.id, team_id: acceptedTeamId }]; invite.use_count += 1; audit(s, invite.activity_id, input.userId, "membership.join", "membership", membership.id, input.requestId); return [{ activity_id: invite.activity_id, membership_id: membership.id, role: membership.role, already_joined: false, team_id: acceptedTeamId ?? "", invite_type: invite.invite_type ?? "activity_member" }]; }); }
export function localRevokeInvite(input: { userId: string; inviteId: string; requestId: string }) { write((s) => { const invite = s.invites.find((x) => x.id === input.inviteId); if (!invite) throw new FormalBoardLocalError("邀请不存在。", 404); const m = member(s, input.userId, invite.activity_id); if (!m || m.role !== "host") throw new FormalBoardLocalError("只有主持人可以撤销邀请。", 403); invite.status = "revoked"; audit(s, invite.activity_id, input.userId, "membership.invite.revoke", "membership", invite.id, input.requestId); }); return []; }
